stations = { 
    "RD": [ 
        { "Code" : "A15", "Name" : "Shady Grove" },
        { "Code" : "A14", "Name" : "Rockville" },
        { "Code" : "A13", "Name" : "Twinbrook" },
        { "Code" : "A12", "Name" : "White Flint" },
        { "Code" : "A11", "Name" : "Grosvenor" },
        { "Code" : "A10", "Name" : "Medical Center" },
        { "Code" : "A09", "Name" : "Bethesda" },
        { "Code" : "A08", "Name" : "Friendship Heights" },
        { "Code" : "A07", "Name" : "Tenleytown" },
        { "Code" : "A06", "Name" : "Van Ness UDC" },
        { "Code" : "A05", "Name" : "Cleveland Park" },
        { "Code" : "A04", "Name" : "Woodley Park Zoo" },
        { "Code" : "A03", "Name" : "Dupont Circle" },
        { "Code" : "A02", "Name" : "Farragut North" },
        { "Code" : "A01", "Name" : "Metro Center" },
        { "Code" : "B01", "Name" : "Gallery Place" },
        { "Code" : "B02", "Name" : "Judiciary Square" },
        { "Code" : "B03", "Name" : "Union Station" },
        { "Code" : "B35", "Name" : "New York Avenue" },
        { "Code" : "B04", "Name" : "Rhode Island Avenue" },
        { "Code" : "B05", "Name" : "Brookland" },
        { "Code" : "B06", "Name" : "Fort Totten" },
        { "Code" : "B07", "Name" : "Takoma" },
        { "Code" : "B08", "Name" : "Silver Spring" },
        { "Code" : "B09", "Name" : "Forest Glen" },
        { "Code" : "B10", "Name" : "Wheaton" },
        { "Code" : "B11", "Name" : "Glenmont" },
    ],
    "OR": [
        {"Code":"K08","Name":"Vienna"},
        {"Code":"K07","Name":"Dunn Loring"},
        {"Code":"K06","Name":"W Falls Church"},
        {"Code":"K05","Name":"E Falls Church"},
        {"Code":"K04","Name":"Ballston","StationTogether1":"","StationTogether2":""},
        {"Code":"K03","Name":"Virginia Square"},
        {"Code":"K02","Name":"Clarendon"},
        {"Code":"K01","Name":"Court House"},
        {"Code":"C05","Name":"Rosslyn"},
        {"Code":"C04","Name":"Foggy Bottom"},
        {"Code":"C03","Name":"Farragut West"},
        {"Code":"C02","Name":"McPherson Square"},
        {"Code":"C01","Name":"Metro Center"},
        {"Code":"D01","Name":"Federal Triangle"},
        {"Code":"D02","Name":"Smithsonian"},
        {"Code":"D03","Name":"L'Enfant Plaza"},
        {"Code":"D04","Name":"Federal Center SW"},
        {"Code":"D05","Name":"Capitol South"},
        {"Code":"D06","Name":"Eastern Market"},
        {"Code":"D07","Name":"Potomac Avenue"},
        {"Code":"D08","Name":"Stadium Armory"},
        {"Code":"D09","Name":"Minnesota Avenue"},
        {"Code":"D10","Name":"Deanwood"},
        {"Code":"D11","Name":"Cheverly"},
        {"Code":"D12","Name":"Landover"},
        {"Code":"D13","Name":"New Carrollton"}
    ],
    "BL": [
        {"Code":"J03","Name":"Franconia-Springf'ld"},
        {"Code":"J02","Name":"Van Dorn St"},
        {"Code":"C13","Name":"King Street"},
        {"Code":"C12","Name":"Braddock Road"},
        {"Code":"C10","Name":"National Arpt"},
        {"Code":"C09","Name":"Crystal City"},
        {"Code":"C08","Name":"Pentagon City"},
        {"Code":"C07","Name":"Pentagon"},
        {"Code":"C06","Name":"Arlington Cemetery"},
        {"Code":"C05","Name":"Rosslyn"},
        {"Code":"C04","Name":"Foggy Bottom"},
        {"Code":"C03","Name":"Farragut West"},
        {"Code":"C02","Name":"McPherson Square"},
        {"Code":"C01","Name":"Metro Center"},
        {"Code":"D01","Name":"Federal Triangle"},
        {"Code":"D02","Name":"Smithsonian"},
        {"Code":"D03","Name":"L'Enfant Plaza"},
        {"Code":"D04","Name":"Federal Center SW"},
        {"Code":"D05","Name":"Capitol South"},
        {"Code":"D06","Name":"Eastern Market"},
        {"Code":"D07","Name":"Potomac Avenue"},
        {"Code":"D08","Name":"Stadium Armory"},
        {"Code":"G01","Name":"Benning Road"},
        {"Code":"G02","Name":"Capitol Heights"},
        {"Code":"G03","Name":"Addison Road"},
        {"Code":"G04","Name":"Morgan Blvd"},
        {"Code":"G05","Name":"Largo Town Center"}
    ],
    "YL": [
        {"Code":"E06","Name":"Fort Totten"},
        {"Code":"E05","Name":"Georgia Avenue"},
        {"Code":"E04","Name":"Columbia Heights"},
        {"Code":"E03","Name":"U Street"},
        {"Code":"E02","Name":"Shaw"},
        {"Code":"E01","Name":"Mt Vernon Sq"},
        {"Code":"F01","Name":"Gallery Place"},
        {"Code":"F02","Name":"Archives"},
        {"Code":"F03","Name":"L'Enfant Plaza"},
        {"Code":"C07","Name":"Pentagon"},
        {"Code":"C08","Name":"Pentagon City"},
        {"Code":"C09","Name":"Crystal City"},
        {"Code":"C10","Name":"National Arpt"},
        {"Code":"C12","Name":"Braddock Road"},
        {"Code":"C13","Name":"King Street"},
        {"Code":"C14","Name":"Eisenhower Avenue"},
        {"Code":"C15","Name":"Huntington"}
    ],
    "GR": [
        {"Code":"E10","Name":"Greenbelt"},
        {"Code":"E09","Name":"College Park"},
        {"Code":"E08","Name":"Prince Georges Plaza"},
        {"Code":"E07","Name":"West Hyattsville"},
        {"Code":"E06","Name":"Fort Totten"},
        {"Code":"E05","Name":"Georgia Avenue"},
        {"Code":"E04","Name":"Columbia Heights"},
        {"Code":"E03","Name":"U Street"},
        {"Code":"E02","Name":"Shaw"},
        {"Code":"E01","Name":"Mt Vernon Sq"},
        {"Code":"F01","Name":"Gallery Place"},
        {"Code":"F02","Name":"Archives"},
        {"Code":"F03","Name":"L'Enfant Plaza"},
        {"Code":"F04","Name":"Waterfront"},
        {"Code":"F05","Name":"Navy Yard"},
        {"Code":"F06","Name":"Anacostia"},
        {"Code":"F07","Name":"Congress Height"},
        {"Code":"F08","Name":"Southern Ave"},
        {"Code":"F09","Name":"Naylor Road"},
        {"Code":"F10","Name":"Suitland"},
        {"Code":"F11","Name":"Branch Avenue"},
    ]
}